# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: CatIsNotFound
subtitle: 'Personal Blog Website'
description: '一个基于 Hexo 框架的个人博客网站'
keywords: '个人博客'
author: CatIsNotFound
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://CatIsNotFound.github.io
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year/:month/:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: redefine
all_minifier: true

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/CatIsNotFound/CatIsNotFound.github.io.git
  branch: 'main'
  # token: ''

feed:
  type: 
    - atom
    - rss2
  path: 
    - atom.xml
    - rss.xml
  limit: false
  order_by: "-date"
  content: false
  content_limit: 60
  content_limit_delim: " "

admin:
  username: catisnotfound
  password_hash:  
  secret: NothingIsSecret

# 统计图表，支持发布文章统计、发布日历、Top标签统计、分类统计、分类雷达。
# see https://www.npmjs.com/package/hexo-butterfly-charts
charts:
  enable: true # 是否启用功能
  postsChart:
    title: 文章发布统计图（每月统计） # 设置文章发布统计的标题，默认为空
    interval: 2 # 横坐标间隔
  tagsChart:
    title: Top 8 标签统计图 # 设置标签统计的标题，默认为空
    interval: 1 # 横坐标间隔
  postsCalendar: 
    title: 文章每日发布日历 # 设置发布日历的标题，默认为空
  categoriesChart:
    title: 分类统计 # 设置分类统计的标题，默认为空
  categoriesRadar:
    title: 分类雷达 # 设置分类雷达的标题，默认为空
  echarts_CDN: # https://lib.baomitu.com/echarts/4.7.0/echarts.min.js
