@echo off  
echo "Cleaning up..."  
call npx hexo clean || echo Failed to clean up. Continuing...  
echo "Deploying..."  
call npx hexo g -d || echo Failed to deploy. Continuing...  
echo "Cleaning up again..."  
call npx hexo clean || echo Failed to clean up. Continuing...  
